export const NEWS_REQUESTED = 'NEWS_REQUESTED';
export const NEWS_RECEIVED = 'NEWS_RECEIVED';
export const NEWS_FAILED = 'NEWS_FAILED';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const AUTH_REQUESTED = 'AUTH_REQUESTED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const VERIFY_REQUESTED = 'VERIFY_REQUESTED';

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';

export const USER_REQUESTED = 'USER_REQUESTED';
export const USER_RECEIVED = 'USER_RECEIVED';
export const USER_FAILED = 'USER_FAILED';

export const SENDING_NEWS_REQUESTED = 'SENDING_NEWS_REQUESTED';
export const SENDING_NEWS_SUCCESS = 'SENDING_NEWS_SUCCESS';
export const SENDING_NEWS_FAILED = 'SENDING_NEWS_FAILED';

export const EDIT_PROFILE_REQUESTED = 'EDIT_PROFILE_REQUESTED';
export const EDIT_PROFILE_SUCCEED = 'EDIT_PROFILE_SUCCEED';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';

export const SEARCH_NEWS = 'SEARCH_NEWS';

export const CHANGE_FILTER = 'CHANGE_FILTER';

export const SWITCH_PAGE = 'SWITCH_PAGE';
