export const NEWS_REQUESTED = 'NEWS_REQUESTED';
export const NEWS_RECEIVED = 'NEWS_RECEIVED';
export const NEWS_FAILED = 'NEWS_FAILED';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const AUTH_REQUESTED = 'AUTH_REQUESTED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const VERIFY_REQUESTED = 'VERIFY_REQUESTED';

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';

export const USER_REQUESTED = 'USER_REQUESTED';
export const USER_RECEIVED = 'USER_RECEIVED';
export const USER_FAILED = 'USER_FAILED';
